### PR TITLE
add codepen iframe with toggle button

### PR DESCRIPTION
**Pull request by qpwo**
Not sure if you want this in here but it would make the tutorial a bit easier to follow / mess with. Not sure if I'm embedding it right and the button style is kinda ugly. Thoughts?

https://user-images.githubusercontent.com/10591373/135768602-2c4092ae-0509-42a9-b288-c565edc63978.mp4

### CODE REVIEW

**Comment by miltoncandelero** [comment]
Wow, that's amazing!

Can you make it so that on each snippet has a link that opens a new codepen?
Maybe the examples would need some rewriting and tinkering so they work but I can do that if you help me with the functionality 👍

**Comment by qpwo** [comment]
https://user-images.githubusercontent.com/10591373/135769302-928eb2bc-037b-4ee0-ba3f-c03cf0ef36f4.mov

Video of current version

**Comment by qpwo** [comment]
Will investigate separate codepens for each example but may need help with slatedoc stuff. Another option may be to copy paste into the editor

**Comment by qpwo** [comment]
Codepen doesn't support having multiple files or any kind of automatic link generation that I'm aware of, and creating a ton of links might get unmanageable. Another option is to use codesandbox or stackblitz and put each example in a file. Here's an example of how that could work:

https://stackblitz.com/edit/pixi-elementals

**Comment by qpwo** [comment]
Another option is to add a toggle in the top-right of pixijselementals.com which substitutes `from 'pixi.js'` to `from "https://cdn.skypack.dev/pixi.js";` and `clampy.png` to `https://raw.githubusercontent.com/miltoncandelero/pixi-hotwire/master/static/clampy.png`. Then automatic copy-paste into codepen iframe wouldn't cause problems. Or that substitution could be done on copy-paste.

**Comment by miltoncandelero** [comment]
Something that allows for typescript + npm packages might be better but a nicely setup codepen might be enough.

 I will check them better once I get to a computer 👍

**Comment by qpwo** [comment]
Yet another option is to use something like https://github.com/microsoft/monaco-editor, and have a button on each section that replaces the contents of the editor with a given example. Then you don't depend on any external free hosting services. Can transpile TS in the browser: https://stackoverflow.com/a/59874612 . Not sure how much time/energy you want to spend on this, though.

**Comment by miltoncandelero** [comment]
I also know that the editor that pixi uses for their code examples has a standalone mode with tabs that allow you  to see the code and then switch to the canvas. 
But that would also mean to move away from slate into another template 🤔

**Pull request closed without merging**
